name: 'Setup AWS EKS'
description: 'Provide a description here'
author: 'Configure a workflow to connect to an EKS cluster'
branding:
  icon: cloud-drizzle
  color: blue
inputs:
  cluster:
    description: 'Name of the EKS cluster to connect to'
    required: true
  context:
    description: '.kube/config context name (default: cluster name)'
  role:
    description: 'ARN of an IAM role to assume for cluster authentication'
  activate:
    description: 'Run `kubectl config use-context` for the newly-created context'
    default: 'false'
runs:
  using: 'node16'
  main: 'dist/index.js'
